### ISSUE TITLE
DB approach and one technical issue

### ISSUE THREAD

**Issue by falconitig** [gjovanov/facer#12]
hello and ty @gjovanov ,

your solution is also a serious

 aid for a project i am working on. But i have 2 inquiries and i hope you can assist me with:

1- what may be the approach to host the detection and recognition on the server side (Database managed)? my aim is identical to the demo you shown so what practical ways to re-implement that?

2- developer and production mode , what are the differences? especially that i ran the project in dev mode and ran the instance but training did not seem to work on dev mode ; so i tried to run with production mode. command "npm run build" worked fine but next command "npm run start" greeted me with errors:

![Screen Shot 2019-12-17 at 11 30 50 PM](https://user-images.githubusercontent.com/13646802/71036109-a7be6200-2125-11ea-98e3-f1d2602c65b9.png)

your effort and help are deeply appreciated sir.

**Comment by gjovanov** [comment]
Hi @falconitig,
`npm run start` basically starts the compiled frontend app using the `pm2` package which in the background creates as many processes as many CPU cores you have. If you are running on an shared hosting, there might be constraints on your user account to do so.

Hence 5 days ago, I added another script inside `package.json` called start-simple, so if you run `npm run start-simple` instead of `npm run start`, then this will start the app only on a sincle CPU core.

In DEV app is started with Hot Reloading, which is useful if you develop and changes the files it auto-start the API and UI.

In PRD everything is compiles, minimizes and optimized for deployment.

You need to provide more details:
- what OS are trying to run this?
- what is the nodejs and npm version (`node -v` and `npm -v`)?
- did u install the packages with `npm i` before all this?
- did u run also the backend app: `npm run api`?

**Comment by falconitig** [comment]
@gjovanov thank you sir for your fast and caring feedback

I am running this on a mac os
node version 10.15.3 , npm 6.4.1
and yes , began with `npm i`
i ran `npm run api` and `npm run dev` the app opened on localhost:3000 and i was able to register and upload pictures but when pressing training , it trains but i notice the loading bar turns to red from white and the recogniser fails to identify my face.

and considering my first inquiry on what is the best approach to transfer training and recognition (basically re-implementing the server hosted demo) in order run multiple client ends on couple of rasperry pi's , any ideas? 

thanks again sir @gjovanov for your support

**Comment by gjovanov** [comment]
Hi @falconitig,
you are right there were two issues that are now fixed if you pull the latest version.

1. `npm run start` wasn't working because `pm2` was missing from the `package.js` so when you restored the packages by running `npm i`, pm2 was missed. This happened because recently I made the effort to upgrade all dependencies/packages to their latest version. Anyways, now its fixed
2. Since the DB of users and user images has grown during the train process, it was failing because the nodejs has a default limit of 5MB JSON that you can post via a request. Now it's increase to 50MB. But keep in mind even this can become too little in case you have too many users you are trying to recognize.

Regarding, the reimplementing it on the server-side, I would suggest to get in touch with the author of face-api.js, because my intention with this demo was purely client-side recognition.

Let me know if now the issues are fixed for you.

**Comment by falconitig** [comment]
@gjovanov thank you sir for your watch and constant support!

i am glad it is fixed , thanks to your efforts again.

considering implementing this on server side , maybe i got mixed up with some concepts. i basically want to make a clone of "facer.xpolrify.net" , do i need some techniques to make this happen or i would just need to put the whole package on a server (host)?

sorry from taking off your valuable time i will make sure to pull the updated version of facer and reply back with results asap :)

**Comment by gjovanov** [comment]
Hi @falconitig,
you can run it manually or via docker.

Manually, involves:
1. `git clone _THIS_REPO_`
2. `cd facer`
3. `npm i`
4. `npm run api`
5. `npm run build`
6. `npm run start`

after that you will have your api listening on `localhost:3001` and the ui server listening on `localhost:3000`.

If you own some kind of domain, the best is to use somekind of proxy e.g. `nginx` and configure it as a reverse proxy like this:
1. `http://your_domain.com` proxied to `http://localholhost:3000`
2. `http://api.your_domain.com` proxied to `http://localhost:3001`
3. once you have the mappings 1. and 2. set up, you can setup your env variable `API_URL` to `http://api.your_domain.com` e.g. on linux `export API_URL=http://api.your_domain.com` and restart the app

Hope it helps.

Let me know if we can close this issue.

**Comment by falconitig** [comment]
@gjovanov thanks sir , 
you have been supportive to extraordinary limits , your info is a huge help :)

and case closed!
